version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: foobar123
      MYSQL_USER: pipefire
      MYSQL_PASSWORD: foobar123
      MYSQL_DATABASE: pipefire
    ports:
      - 3306:3305
