version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: foobar123
      MYSQL_USER: pipefire
      MYSQL_PASSWORD: foobar123
      MYSQL_DATABASE: pipefire
    ports:
      - 3306:3306
    networks:
      app_net:
        ipv4_address: 172.20.1.2
  bfp:
    build:      
      context: ./docker-sshd/
    image: "masenocturnal/sshd:latest" 
    environment:
      SSH_USERS: "test:1002:1002"
      SFTP_MODE: "true" 
    ports:
      - 22
    volumes:
      - ./bfp:/data
      - ~/.ssh/id_rsa.pub:/etc/authorized_keys/test
    networks:
      app_net:
        ipv4_address: 172.20.1.3
  anz:
    image: "masenocturnal/sshd:latest"      
    environment:
      SSH_USERS: "test:1002:1002"      
    ports:
      - 22
    volumes:
      - ~/.ssh/id_rsa.pub:/etc/authorized_keys/test
      - sftp-data:/data
    networks:
      app_net:
        ipv4_address: 172.20.1.4
  px:
    image: "masenocturnal/sshd:latest"    
    environment:
      SSH_USERS: "test:1002:1002"
    ports:
      - 22
    volumes:
      - ~/.ssh/id_rsa.pub:/etc/authorized_keys/test
      - sftp-data:/data
    networks:
      app_net:
        ipv4_address: 172.20.1.5
  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
      - "5671:5671"
      - "15672:15672"
      - "15671:15671"
    networks:
      app_net:
        ipv4_address: 172.20.1.6
networks:
  app_net:
    ipam:
      config:
        - subnet: 172.20.1.0/24

volumes:
  sftp-data:
